typography_spectrum: 0.5498180519789457
color:
  brandStrength: 0.1601053741760552
  lightness: 0.6679920696187764
  saturation: 0.7957177262287587
  rhythmicContrast: 0.93121277843602
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
layout_spectrum: 0.660039619076997
author:
  name: Memo
  email: frontdesk@aldora.com
  url: aldora.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a088a692-b9ff-4672-bd12-6300ec63bfa5.png
name: Aldora Divers
navigation:
  - name: Aldora Divers
    url: aldora.com
    type: external
title: '"Dive the rest of Cozumel"'
